Change to Decorators Pattern
carreraprogrammer/school pull request #3
Opened 2023-02-09 15:11 UTC by carreraprogrammer

## PROJECT REQUIREMENTS

- [ ]  Check the usage of [Decorator pattern in Ruby](https://refactoring.guru/design-patterns/decorator/ruby/example#example-0)
- [ ]  Think about how you can use two decorators in order to capitalize and trim people's names.
In the following steps you will get instructions for implementing the Decorator design pattern for this case.

### Interface 

- Create a class Nameable.
- [ ]  Implement a method called correct_name that will raise a NotImplementedError.

###Prepare base Decorator

- [ ]  Make sure that it inherits from Nameable.
- [ ] In the constructor assign a nameable object from params to an instance variable.
Implement the correct_name method that returns the result of the correct_name method of the @nameable.

### Prepare CapitalizeDecorator and TrimmerDecorator

- For the CapitalizeDecorator:
- [ ]Create a class that inherits from the base Decorator class.
- [ ]Implement a method correct_name that capitalizes the output of @nameable.correct_name.
- For the TrimmerDecorator:
- [ ]Create a class that inherits from the base Decorator class.
- [ ] Implement a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

### See your decorators in action

2023-02-09 17:07 UTC, m05e5 requested changes
Hi @carreraprogrammer , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that still has linters errors in it. kindly make sure you fix all of them before requesting another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-09 19:37 UTC, carreraprogrammer commented
Thank you @m05e5, I didn't notice it. I have all the linters approved now  😁

2023-02-09 23:02 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi @carreraprogrammer 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ Use decorators 📌 
✔️ Good commit history
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-09 23:02 UTC, codepantha commented on capitalize_decorator.rb
> +    @nameable_object.correct_name.upcase
- [x] The CapitalizeDecorator is expected to capitalize the first letter of the correct name rather than make the whole thing uppercase as you have done here 👇. Please use `correct_name.capitalize` instead of `correct_name.upcase` 😎
![image](https://user-images.githubusercontent.com/46839548/217958004-a3361d74-f679-4023-8d8e-3b90000d6526.png)

2023-02-09 23:04 UTC, carreraprogrammer commented on capitalize_decorator.rb
> +    @nameable_object.correct_name.upcase
Thank you very much @codepantha, I'll do it right now! 😁

2023-02-10 02:36 UTC, hiromataba approved these changes
# Status: Approved :tada: :tada: :tada: 
Hi @carreraprogrammer     :wave: :wave: 

![200w](https://user-images.githubusercontent.com/75126481/151663786-7e0aa330-6769-4ab2-a051-3754be515be9.gif)  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-10 14:11 UTC, merged